<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE eagle SYSTEM "eagle.dtd">
<eagle version="7.5.0">
<drawing>
<settings>
<setting alwaysvectorfont="no"/>
<setting verticaltext="up"/>
</settings>
<grid distance="0.1" unitdist="inch" unit="inch" style="lines" multiple="1" display="no" altdistance="0.01" altunitdist="inch" altunit="inch"/>
<layers>
<layer number="1" name="Top" color="4" fill="9" visible="no" active="no"/>
<layer number="16" name="Bottom" color="1" fill="1" visible="no" active="no"/>
<layer number="17" name="Pads" color="2" fill="1" visible="no" active="no"/>
<layer number="18" name="Vias" color="2" fill="1" visible="no" active="no"/>
<layer number="19" name="Unrouted" color="6" fill="1" visible="no" active="no"/>
<layer number="20" name="Dimension" color="15" fill="1" visible="no" active="no"/>
<layer number="21" name="tPlace" color="7" fill="1" visible="no" active="no"/>
<layer number="22" name="bPlace" color="7" fill="1" visible="no" active="no"/>
<layer number="23" name="tOrigins" color="15" fill="1" visible="no" active="no"/>
<layer number="24" name="bOrigins" color="15" fill="1" visible="no" active="no"/>
<layer number="25" name="tNames" color="7" fill="1" visible="no" active="no"/>
<layer number="26" name="bNames" color="7" fill="1" visible="no" active="no"/>
<layer number="27" name="tValues" color="7" fill="1" visible="no" active="no"/>
<layer number="28" name="bValues" color="7" fill="1" visible="no" active="no"/>
<layer number="29" name="tStop" color="7" fill="3" visible="no" active="no"/>
<layer number="30" name="bStop" color="7" fill="6" visible="no" active="no"/>
<layer number="31" name="tCream" color="7" fill="4" visible="no" active="no"/>
<layer number="32" name="bCream" color="7" fill="5" visible="no" active="no"/>
<layer number="33" name="tFinish" color="6" fill="3" visible="no" active="no"/>
<layer number="34" name="bFinish" color="6" fill="6" visible="no" active="no"/>
<layer number="35" name="tGlue" color="7" fill="4" visible="no" active="no"/>
<layer number="36" name="bGlue" color="7" fill="5" visible="no" active="no"/>
<layer number="37" name="tTest" color="7" fill="1" visible="no" active="no"/>
<layer number="38" name="bTest" color="7" fill="1" visible="no" active="no"/>
<layer number="39" name="tKeepout" color="4" fill="11" visible="no" active="no"/>
<layer number="40" name="bKeepout" color="1" fill="11" visible="no" active="no"/>
<layer number="41" name="tRestrict" color="4" fill="10" visible="no" active="no"/>
<layer number="42" name="bRestrict" color="1" fill="10" visible="no" active="no"/>
<layer number="43" name="vRestrict" color="2" fill="10" visible="no" active="no"/>
<layer number="44" name="Drills" color="7" fill="1" visible="no" active="no"/>
<layer number="45" name="Holes" color="7" fill="1" visible="no" active="no"/>
<layer number="46" name="Milling" color="3" fill="1" visible="no" active="no"/>
<layer number="47" name="Measures" color="7" fill="1" visible="no" active="no"/>
<layer number="48" name="Document" color="7" fill="1" visible="no" active="no"/>
<layer number="49" name="Reference" color="7" fill="1" visible="no" active="no"/>
<layer number="51" name="tDocu" color="6" fill="1" visible="no" active="no"/>
<layer number="52" name="bDocu" color="7" fill="1" visible="no" active="no"/>
<layer number="90" name="Modules" color="5" fill="1" visible="yes" active="yes"/>
<layer number="91" name="Nets" color="2" fill="1" visible="yes" active="yes"/>
<layer number="92" name="Busses" color="1" fill="1" visible="yes" active="yes"/>
<layer number="93" name="Pins" color="2" fill="1" visible="no" active="yes"/>
<layer number="94" name="Symbols" color="4" fill="1" visible="yes" active="yes"/>
<layer number="95" name="Names" color="7" fill="1" visible="yes" active="yes"/>
<layer number="96" name="Values" color="7" fill="1" visible="yes" active="yes"/>
<layer number="97" name="Info" color="7" fill="1" visible="yes" active="yes"/>
<layer number="98" name="Guide" color="6" fill="1" visible="yes" active="yes"/>
</layers>
<schematic xreflabel="%F%N/%S.%C%R" xrefpart="/%S.%C%R">
<libraries>
<library name="texas">
<description>&lt;b&gt;Texas Instruments Devices&lt;/b&gt;&lt;p&gt;
 &lt;author&gt;Created by librarian@cadsoft.de&lt;/author&gt;</description>
<packages>
<package name="TSSOP38_R-PDSO-G38-DA">
<description>&lt;b&gt;TSSOP 38&lt;/b&gt; DA (R-PDSO-G38)&lt;p&gt;
Auto generated by &lt;i&gt;make-symbol-device-package-bsdl.ulp Rev. 28&lt;/i&gt;&lt;br&gt;
Source: http://focus.ti.com/lit/ds/symlink/msp430f2274.pdf</description>
<wire x1="6.1984" y1="-2.9984" x2="6.1984" y2="2.9984" width="0.2032" layer="21"/>
<wire x1="6.1984" y1="2.9984" x2="-6.1984" y2="2.9984" width="0.2032" layer="21"/>
<wire x1="-6.1984" y1="2.9984" x2="-6.1984" y2="-2.9984" width="0.2032" layer="21"/>
<wire x1="-6.1984" y1="-2.9984" x2="6.1984" y2="-2.9984" width="0.2032" layer="21"/>
<circle x="-5.4" y="-2.225" radius="0.3335" width="0" layer="21"/>
<smd name="1" x="-5.85" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="2" x="-5.2" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="3" x="-4.55" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="4" x="-3.9" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="5" x="-3.25" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="6" x="-2.6" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="7" x="-1.95" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="8" x="-1.3" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="9" x="-0.65" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="10" x="0" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="11" x="0.65" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="12" x="1.3" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="13" x="1.95" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="14" x="2.6" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="15" x="3.25" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="16" x="3.9" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="17" x="4.55" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="18" x="5.2" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="19" x="5.85" y="-3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="20" x="5.85" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="21" x="5.2" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="22" x="4.55" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="23" x="3.9" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="24" x="3.25" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="25" x="2.6" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="26" x="1.95" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="27" x="1.3" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="28" x="0.65" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="29" x="0" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="30" x="-0.65" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="31" x="-1.3" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="32" x="-1.95" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="33" x="-2.6" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="34" x="-3.25" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="35" x="-3.9" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="36" x="-4.55" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="37" x="-5.2" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<smd name="38" x="-5.85" y="3.85" dx="1" dy="0.35" layer="1" rot="R90"/>
<text x="-6.35" y="-2.54" size="1.27" layer="25" rot="R90">&gt;NAME</text>
<text x="-3.81" y="-0.635" size="1.27" layer="27">&gt;VALUE</text>
<rectangle x1="-6.375" y1="-3.775" x2="-5.325" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="-5.725" y1="-3.775" x2="-4.675" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="-5.075" y1="-3.775" x2="-4.025" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="-4.425" y1="-3.775" x2="-3.375" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="-3.775" y1="-3.775" x2="-2.725" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="-3.125" y1="-3.775" x2="-2.075" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="-2.475" y1="-3.775" x2="-1.425" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="-1.825" y1="-3.775" x2="-0.775" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="-1.175" y1="-3.775" x2="-0.125" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="-0.525" y1="-3.775" x2="0.525" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="0.125" y1="-3.775" x2="1.175" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="0.775" y1="-3.775" x2="1.825" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="1.425" y1="-3.775" x2="2.475" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="2.075" y1="-3.775" x2="3.125" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="2.725" y1="-3.775" x2="3.775" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="3.375" y1="-3.775" x2="4.425" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="4.025" y1="-3.775" x2="5.075" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="4.675" y1="-3.775" x2="5.725" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="5.325" y1="-3.775" x2="6.375" y2="-3.475" layer="51" rot="R90"/>
<rectangle x1="5.325" y1="3.475" x2="6.375" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="4.675" y1="3.475" x2="5.725" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="4.025" y1="3.475" x2="5.075" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="3.375" y1="3.475" x2="4.425" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="2.725" y1="3.475" x2="3.775" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="2.075" y1="3.475" x2="3.125" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="1.425" y1="3.475" x2="2.475" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="0.775" y1="3.475" x2="1.825" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="0.125" y1="3.475" x2="1.175" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-0.525" y1="3.475" x2="0.525" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-1.175" y1="3.475" x2="-0.125" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-1.825" y1="3.475" x2="-0.775" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-2.475" y1="3.475" x2="-1.425" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-3.125" y1="3.475" x2="-2.075" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-3.775" y1="3.475" x2="-2.725" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-4.425" y1="3.475" x2="-3.375" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-5.075" y1="3.475" x2="-4.025" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-5.725" y1="3.475" x2="-4.675" y2="3.775" layer="51" rot="R90"/>
<rectangle x1="-6.375" y1="3.475" x2="-5.325" y2="3.775" layer="51" rot="R90"/>
</package>
</packages>
<symbols>
<symbol name="MSP430X22X4-DA">
<wire x1="-43.18" y1="-25.4" x2="43.18" y2="-25.4" width="0.2032" layer="94"/>
<wire x1="43.18" y1="-25.4" x2="43.18" y2="25.4" width="0.2032" layer="94"/>
<wire x1="43.18" y1="25.4" x2="-43.18" y2="25.4" width="0.2032" layer="94"/>
<wire x1="-43.18" y1="25.4" x2="-43.18" y2="-25.4" width="0.2032" layer="94"/>
<text x="-43.18" y="26.67" size="1.778" layer="95">&gt;NAME</text>
<text x="-43.18" y="-27.94" size="1.778" layer="96">&gt;VALUE</text>
<pin name="TEST/SBWTCK" x="-48.26" y="22.86" length="middle" direction="in"/>
<pin name="DVCC" x="-48.26" y="20.32" length="middle" direction="pwr"/>
<pin name="P2.5/ROSC" x="-48.26" y="17.78" length="middle"/>
<pin name="DVSS" x="-48.26" y="15.24" length="middle" direction="pwr"/>
<pin name="XOUT/P2.7" x="-48.26" y="12.7" length="middle"/>
<pin name="XIN/P2.6" x="-48.26" y="10.16" length="middle"/>
<pin name="!RST!/NMI/SBWTDIO" x="-48.26" y="7.62" length="middle" direction="in"/>
<pin name="P2.0/ACLK/A0/OA0I0" x="-48.26" y="5.08" length="middle"/>
<pin name="P2.1/TAINCLK/SMCLK/A1/OA0O" x="-48.26" y="2.54" length="middle"/>
<pin name="P2.2/TA0/A2/OA0I1" x="-48.26" y="0" length="middle"/>
<pin name="P3.0/UCB0STE/UCA0CLK/A5" x="-48.26" y="-2.54" length="middle"/>
<pin name="P3.1/UCB0SIMO/UCB0SDA" x="-48.26" y="-5.08" length="middle"/>
<pin name="P3.2/UCB0SOMI/UCB0SCL" x="-48.26" y="-7.62" length="middle"/>
<pin name="P3.3/UCB0CLK/UCA0STE" x="-48.26" y="-10.16" length="middle"/>
<pin name="AVSS" x="-48.26" y="-12.7" length="middle" direction="pwr"/>
<pin name="AVCC" x="-48.26" y="-15.24" length="middle" direction="pwr"/>
<pin name="P4.0/TB0" x="-48.26" y="-17.78" length="middle"/>
<pin name="P4.1/TB1" x="-48.26" y="-20.32" length="middle"/>
<pin name="P4.2/TB2" x="-48.26" y="-22.86" length="middle"/>
<pin name="P4.3/TB0/A12/OA0O" x="48.26" y="-22.86" length="middle" rot="R180"/>
<pin name="P4.4/TB1A13/OA1O" x="48.26" y="-20.32" length="middle" rot="R180"/>
<pin name="P4.5/TB2A14/OA0I3" x="48.26" y="-17.78" length="middle" rot="R180"/>
<pin name="P4.6/TBOUTHA15/OA1I3" x="48.26" y="-15.24" length="middle" rot="R180"/>
<pin name="P4.7/TBCLK" x="48.26" y="-12.7" length="middle" rot="R180"/>
<pin name="P3.4/UCA0TXD/UCA0SIMO" x="48.26" y="-10.16" length="middle" rot="R180"/>
<pin name="P3.5/UCA0RXD/UCA0SOMI" x="48.26" y="-7.62" length="middle" rot="R180"/>
<pin name="P3.6/A6/OA0I2" x="48.26" y="-5.08" length="middle" rot="R180"/>
<pin name="P3.7/A7/OA1I2" x="48.26" y="-2.54" length="middle" rot="R180"/>
<pin name="P2.3/TA1/A3/VREF-/VEREF-/OA1I1/OA1O" x="48.26" y="0" length="middle" rot="R180"/>
<pin name="P2.4/TA2/A4/VREF+/VEREF+/OA1I0" x="48.26" y="2.54" length="middle" rot="R180"/>
<pin name="P1.0/TACLK/ADC10CLK" x="48.26" y="5.08" length="middle" rot="R180"/>
<pin name="P1.1/TA0" x="48.26" y="7.62" length="middle" rot="R180"/>
<pin name="P1.2/TA1" x="48.26" y="10.16" length="middle" rot="R180"/>
<pin name="P1.3/TA2" x="48.26" y="12.7" length="middle" rot="R180"/>
<pin name="P1.4/SMCLK/TCK" x="48.26" y="15.24" length="middle" rot="R180"/>
<pin name="P1.5/TA0/TMS" x="48.26" y="17.78" length="middle" rot="R180"/>
<pin name="P1.6/TA1/TDI/TCLK" x="48.26" y="20.32" length="middle" rot="R180"/>
<pin name="P1.7/TA2/TDO/TDI" x="48.26" y="22.86" length="middle" rot="R180"/>
</symbol>
</symbols>
<devicesets>
<deviceset name="MSP430F22*4IDA" prefix="IC">
<description>&lt;b&gt;MIXED SIGNAL MICROCONTROLLER&lt;/b&gt;
Source: http://focus.ti.com/lit/ds/symlink/msp430f2274.pdf</description>
<gates>
<gate name="G$1" symbol="MSP430X22X4-DA" x="0" y="0"/>
</gates>
<devices>
<device name="" package="TSSOP38_R-PDSO-G38-DA">
<connects>
<connect gate="G$1" pin="!RST!/NMI/SBWTDIO" pad="7"/>
<connect gate="G$1" pin="AVCC" pad="16"/>
<connect gate="G$1" pin="AVSS" pad="15"/>
<connect gate="G$1" pin="DVCC" pad="2"/>
<connect gate="G$1" pin="DVSS" pad="4"/>
<connect gate="G$1" pin="P1.0/TACLK/ADC10CLK" pad="31"/>
<connect gate="G$1" pin="P1.1/TA0" pad="32"/>
<connect gate="G$1" pin="P1.2/TA1" pad="33"/>
<connect gate="G$1" pin="P1.3/TA2" pad="34"/>
<connect gate="G$1" pin="P1.4/SMCLK/TCK" pad="35"/>
<connect gate="G$1" pin="P1.5/TA0/TMS" pad="36"/>
<connect gate="G$1" pin="P1.6/TA1/TDI/TCLK" pad="37"/>
<connect gate="G$1" pin="P1.7/TA2/TDO/TDI" pad="38"/>
<connect gate="G$1" pin="P2.0/ACLK/A0/OA0I0" pad="8"/>
<connect gate="G$1" pin="P2.1/TAINCLK/SMCLK/A1/OA0O" pad="9"/>
<connect gate="G$1" pin="P2.2/TA0/A2/OA0I1" pad="10"/>
<connect gate="G$1" pin="P2.3/TA1/A3/VREF-/VEREF-/OA1I1/OA1O" pad="29"/>
<connect gate="G$1" pin="P2.4/TA2/A4/VREF+/VEREF+/OA1I0" pad="30"/>
<connect gate="G$1" pin="P2.5/ROSC" pad="3"/>
<connect gate="G$1" pin="P3.0/UCB0STE/UCA0CLK/A5" pad="11"/>
<connect gate="G$1" pin="P3.1/UCB0SIMO/UCB0SDA" pad="12"/>
<connect gate="G$1" pin="P3.2/UCB0SOMI/UCB0SCL" pad="13"/>
<connect gate="G$1" pin="P3.3/UCB0CLK/UCA0STE" pad="14"/>
<connect gate="G$1" pin="P3.4/UCA0TXD/UCA0SIMO" pad="25"/>
<connect gate="G$1" pin="P3.5/UCA0RXD/UCA0SOMI" pad="26"/>
<connect gate="G$1" pin="P3.6/A6/OA0I2" pad="27"/>
<connect gate="G$1" pin="P3.7/A7/OA1I2" pad="28"/>
<connect gate="G$1" pin="P4.0/TB0" pad="17"/>
<connect gate="G$1" pin="P4.1/TB1" pad="18"/>
<connect gate="G$1" pin="P4.2/TB2" pad="19"/>
<connect gate="G$1" pin="P4.3/TB0/A12/OA0O" pad="20"/>
<connect gate="G$1" pin="P4.4/TB1A13/OA1O" pad="21"/>
<connect gate="G$1" pin="P4.5/TB2A14/OA0I3" pad="22"/>
<connect gate="G$1" pin="P4.6/TBOUTHA15/OA1I3" pad="23"/>
<connect gate="G$1" pin="P4.7/TBCLK" pad="24"/>
<connect gate="G$1" pin="TEST/SBWTCK" pad="1"/>
<connect gate="G$1" pin="XIN/P2.6" pad="6"/>
<connect gate="G$1" pin="XOUT/P2.7" pad="5"/>
</connects>
<technologies>
<technology name="3">
<attribute name="MF" value="" constant="no"/>
<attribute name="MPN" value="MSP430F2234IDA" constant="no"/>
<attribute name="OC_FARNELL" value="1649419" constant="no"/>
<attribute name="OC_NEWARK" value="28M6320" constant="no"/>
</technology>
<technology name="5">
<attribute name="MF" value="" constant="no"/>
<attribute name="MPN" value="MSP430F2254IDA" constant="no"/>
<attribute name="OC_FARNELL" value="1649422" constant="no"/>
<attribute name="OC_NEWARK" value="28M6334" constant="no"/>
</technology>
<technology name="7">
<attribute name="MF" value="" constant="no"/>
<attribute name="MPN" value="MSP430F2274IDA" constant="no"/>
<attribute name="OC_FARNELL" value="1610179" constant="no"/>
<attribute name="OC_NEWARK" value="28M6350" constant="no"/>
</technology>
</technologies>
</device>
</devices>
</deviceset>
</devicesets>
</library>
<library name="pinhead">
<description>&lt;b&gt;Pin Header Connectors&lt;/b&gt;&lt;p&gt;
&lt;author&gt;Created by librarian@cadsoft.de&lt;/author&gt;</description>
<packages>
<package name="1X19">
<description>&lt;b&gt;PIN HEADER&lt;/b&gt;</description>
<wire x1="19.05" y1="0.635" x2="19.685" y2="1.27" width="0.1524" layer="21"/>
<wire x1="19.685" y1="1.27" x2="20.955" y2="1.27" width="0.1524" layer="21"/>
<wire x1="20.955" y1="1.27" x2="21.59" y2="0.635" width="0.1524" layer="21"/>
<wire x1="21.59" y1="0.635" x2="21.59" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="21.59" y1="-0.635" x2="20.955" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="20.955" y1="-1.27" x2="19.685" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="19.685" y1="-1.27" x2="19.05" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="14.605" y1="1.27" x2="15.875" y2="1.27" width="0.1524" layer="21"/>
<wire x1="15.875" y1="1.27" x2="16.51" y2="0.635" width="0.1524" layer="21"/>
<wire x1="16.51" y1="0.635" x2="16.51" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="16.51" y1="-0.635" x2="15.875" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="16.51" y1="0.635" x2="17.145" y2="1.27" width="0.1524" layer="21"/>
<wire x1="17.145" y1="1.27" x2="18.415" y2="1.27" width="0.1524" layer="21"/>
<wire x1="18.415" y1="1.27" x2="19.05" y2="0.635" width="0.1524" layer="21"/>
<wire x1="19.05" y1="0.635" x2="19.05" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="19.05" y1="-0.635" x2="18.415" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="18.415" y1="-1.27" x2="17.145" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="17.145" y1="-1.27" x2="16.51" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="11.43" y1="0.635" x2="12.065" y2="1.27" width="0.1524" layer="21"/>
<wire x1="12.065" y1="1.27" x2="13.335" y2="1.27" width="0.1524" layer="21"/>
<wire x1="13.335" y1="1.27" x2="13.97" y2="0.635" width="0.1524" layer="21"/>
<wire x1="13.97" y1="0.635" x2="13.97" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="13.97" y1="-0.635" x2="13.335" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="13.335" y1="-1.27" x2="12.065" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="12.065" y1="-1.27" x2="11.43" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="14.605" y1="1.27" x2="13.97" y2="0.635" width="0.1524" layer="21"/>
<wire x1="13.97" y1="-0.635" x2="14.605" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="15.875" y1="-1.27" x2="14.605" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="6.985" y1="1.27" x2="8.255" y2="1.27" width="0.1524" layer="21"/>
<wire x1="8.255" y1="1.27" x2="8.89" y2="0.635" width="0.1524" layer="21"/>
<wire x1="8.89" y1="0.635" x2="8.89" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="8.89" y1="-0.635" x2="8.255" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="8.89" y1="0.635" x2="9.525" y2="1.27" width="0.1524" layer="21"/>
<wire x1="9.525" y1="1.27" x2="10.795" y2="1.27" width="0.1524" layer="21"/>
<wire x1="10.795" y1="1.27" x2="11.43" y2="0.635" width="0.1524" layer="21"/>
<wire x1="11.43" y1="0.635" x2="11.43" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="11.43" y1="-0.635" x2="10.795" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="10.795" y1="-1.27" x2="9.525" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="9.525" y1="-1.27" x2="8.89" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="3.81" y1="0.635" x2="4.445" y2="1.27" width="0.1524" layer="21"/>
<wire x1="4.445" y1="1.27" x2="5.715" y2="1.27" width="0.1524" layer="21"/>
<wire x1="5.715" y1="1.27" x2="6.35" y2="0.635" width="0.1524" layer="21"/>
<wire x1="6.35" y1="0.635" x2="6.35" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="6.35" y1="-0.635" x2="5.715" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="5.715" y1="-1.27" x2="4.445" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="4.445" y1="-1.27" x2="3.81" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="6.985" y1="1.27" x2="6.35" y2="0.635" width="0.1524" layer="21"/>
<wire x1="6.35" y1="-0.635" x2="6.985" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="8.255" y1="-1.27" x2="6.985" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-0.635" y1="1.27" x2="0.635" y2="1.27" width="0.1524" layer="21"/>
<wire x1="0.635" y1="1.27" x2="1.27" y2="0.635" width="0.1524" layer="21"/>
<wire x1="1.27" y1="0.635" x2="1.27" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="1.27" y1="-0.635" x2="0.635" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="1.27" y1="0.635" x2="1.905" y2="1.27" width="0.1524" layer="21"/>
<wire x1="1.905" y1="1.27" x2="3.175" y2="1.27" width="0.1524" layer="21"/>
<wire x1="3.175" y1="1.27" x2="3.81" y2="0.635" width="0.1524" layer="21"/>
<wire x1="3.81" y1="0.635" x2="3.81" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="3.81" y1="-0.635" x2="3.175" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="3.175" y1="-1.27" x2="1.905" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="1.905" y1="-1.27" x2="1.27" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-3.81" y1="0.635" x2="-3.175" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-3.175" y1="1.27" x2="-1.905" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-1.905" y1="1.27" x2="-1.27" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-1.27" y1="0.635" x2="-1.27" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-1.27" y1="-0.635" x2="-1.905" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-1.905" y1="-1.27" x2="-3.175" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-3.175" y1="-1.27" x2="-3.81" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-0.635" y1="1.27" x2="-1.27" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-1.27" y1="-0.635" x2="-0.635" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="0.635" y1="-1.27" x2="-0.635" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-8.255" y1="1.27" x2="-6.985" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-6.985" y1="1.27" x2="-6.35" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-6.35" y1="0.635" x2="-6.35" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-6.35" y1="-0.635" x2="-6.985" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-6.35" y1="0.635" x2="-5.715" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-5.715" y1="1.27" x2="-4.445" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-4.445" y1="1.27" x2="-3.81" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-3.81" y1="0.635" x2="-3.81" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-3.81" y1="-0.635" x2="-4.445" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-4.445" y1="-1.27" x2="-5.715" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-5.715" y1="-1.27" x2="-6.35" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-11.43" y1="0.635" x2="-10.795" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-10.795" y1="1.27" x2="-9.525" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-9.525" y1="1.27" x2="-8.89" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-8.89" y1="0.635" x2="-8.89" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-8.89" y1="-0.635" x2="-9.525" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-9.525" y1="-1.27" x2="-10.795" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-10.795" y1="-1.27" x2="-11.43" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-8.255" y1="1.27" x2="-8.89" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-8.89" y1="-0.635" x2="-8.255" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-6.985" y1="-1.27" x2="-8.255" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-15.875" y1="1.27" x2="-14.605" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-14.605" y1="1.27" x2="-13.97" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-13.97" y1="0.635" x2="-13.97" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-13.97" y1="-0.635" x2="-14.605" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-13.97" y1="0.635" x2="-13.335" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-13.335" y1="1.27" x2="-12.065" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-12.065" y1="1.27" x2="-11.43" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-11.43" y1="0.635" x2="-11.43" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-11.43" y1="-0.635" x2="-12.065" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-12.065" y1="-1.27" x2="-13.335" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-13.335" y1="-1.27" x2="-13.97" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-19.05" y1="0.635" x2="-18.415" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-18.415" y1="1.27" x2="-17.145" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-17.145" y1="1.27" x2="-16.51" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-16.51" y1="0.635" x2="-16.51" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-16.51" y1="-0.635" x2="-17.145" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-17.145" y1="-1.27" x2="-18.415" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-18.415" y1="-1.27" x2="-19.05" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-15.875" y1="1.27" x2="-16.51" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-16.51" y1="-0.635" x2="-15.875" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-14.605" y1="-1.27" x2="-15.875" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-23.495" y1="1.27" x2="-22.225" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-22.225" y1="1.27" x2="-21.59" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-21.59" y1="0.635" x2="-21.59" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-21.59" y1="-0.635" x2="-22.225" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-21.59" y1="0.635" x2="-20.955" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-20.955" y1="1.27" x2="-19.685" y2="1.27" width="0.1524" layer="21"/>
<wire x1="-19.685" y1="1.27" x2="-19.05" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-19.05" y1="0.635" x2="-19.05" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-19.05" y1="-0.635" x2="-19.685" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-19.685" y1="-1.27" x2="-20.955" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-20.955" y1="-1.27" x2="-21.59" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-24.13" y1="0.635" x2="-24.13" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="-23.495" y1="1.27" x2="-24.13" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-24.13" y1="-0.635" x2="-23.495" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="-22.225" y1="-1.27" x2="-23.495" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="21.59" y1="0.635" x2="22.225" y2="1.27" width="0.1524" layer="21"/>
<wire x1="22.225" y1="1.27" x2="23.495" y2="1.27" width="0.1524" layer="21"/>
<wire x1="23.495" y1="1.27" x2="24.13" y2="0.635" width="0.1524" layer="21"/>
<wire x1="24.13" y1="0.635" x2="24.13" y2="-0.635" width="0.1524" layer="21"/>
<wire x1="24.13" y1="-0.635" x2="23.495" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="23.495" y1="-1.27" x2="22.225" y2="-1.27" width="0.1524" layer="21"/>
<wire x1="22.225" y1="-1.27" x2="21.59" y2="-0.635" width="0.1524" layer="21"/>
<pad name="1" x="-22.86" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="2" x="-20.32" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="3" x="-17.78" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="4" x="-15.24" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="5" x="-12.7" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="6" x="-10.16" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="7" x="-7.62" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="8" x="-5.08" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="9" x="-2.54" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="10" x="0" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="11" x="2.54" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="12" x="5.08" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="13" x="7.62" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="14" x="10.16" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="15" x="12.7" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="16" x="15.24" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="17" x="17.78" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="18" x="20.32" y="0" drill="1.016" shape="long" rot="R90"/>
<pad name="19" x="22.86" y="0" drill="1.016" shape="long" rot="R90"/>
<text x="-24.2062" y="1.8288" size="1.27" layer="25" ratio="10">&gt;NAME</text>
<text x="-24.13" y="-3.175" size="1.27" layer="27">&gt;VALUE</text>
<rectangle x1="20.066" y1="-0.254" x2="20.574" y2="0.254" layer="51"/>
<rectangle x1="17.526" y1="-0.254" x2="18.034" y2="0.254" layer="51"/>
<rectangle x1="14.986" y1="-0.254" x2="15.494" y2="0.254" layer="51"/>
<rectangle x1="12.446" y1="-0.254" x2="12.954" y2="0.254" layer="51"/>
<rectangle x1="9.906" y1="-0.254" x2="10.414" y2="0.254" layer="51"/>
<rectangle x1="7.366" y1="-0.254" x2="7.874" y2="0.254" layer="51"/>
<rectangle x1="4.826" y1="-0.254" x2="5.334" y2="0.254" layer="51"/>
<rectangle x1="2.286" y1="-0.254" x2="2.794" y2="0.254" layer="51"/>
<rectangle x1="-0.254" y1="-0.254" x2="0.254" y2="0.254" layer="51"/>
<rectangle x1="-2.794" y1="-0.254" x2="-2.286" y2="0.254" layer="51"/>
<rectangle x1="-5.334" y1="-0.254" x2="-4.826" y2="0.254" layer="51"/>
<rectangle x1="-7.874" y1="-0.254" x2="-7.366" y2="0.254" layer="51"/>
<rectangle x1="-10.414" y1="-0.254" x2="-9.906" y2="0.254" layer="51"/>
<rectangle x1="-12.954" y1="-0.254" x2="-12.446" y2="0.254" layer="51"/>
<rectangle x1="-15.494" y1="-0.254" x2="-14.986" y2="0.254" layer="51"/>
<rectangle x1="-18.034" y1="-0.254" x2="-17.526" y2="0.254" layer="51"/>
<rectangle x1="-20.574" y1="-0.254" x2="-20.066" y2="0.254" layer="51"/>
<rectangle x1="-23.114" y1="-0.254" x2="-22.606" y2="0.254" layer="51"/>
<rectangle x1="22.606" y1="-0.254" x2="23.114" y2="0.254" layer="51"/>
</package>
<package name="1X19/90">
<description>&lt;b&gt;PIN HEADER&lt;/b&gt;</description>
<wire x1="-24.13" y1="-1.905" x2="-21.59" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-21.59" y1="-1.905" x2="-21.59" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-21.59" y1="0.635" x2="-24.13" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-24.13" y1="0.635" x2="-24.13" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-22.86" y1="6.985" x2="-22.86" y2="1.27" width="0.762" layer="21"/>
<wire x1="-21.59" y1="-1.905" x2="-19.05" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-19.05" y1="-1.905" x2="-19.05" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-19.05" y1="0.635" x2="-21.59" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-20.32" y1="6.985" x2="-20.32" y2="1.27" width="0.762" layer="21"/>
<wire x1="-19.05" y1="-1.905" x2="-16.51" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-16.51" y1="-1.905" x2="-16.51" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-16.51" y1="0.635" x2="-19.05" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-17.78" y1="6.985" x2="-17.78" y2="1.27" width="0.762" layer="21"/>
<wire x1="-16.51" y1="-1.905" x2="-13.97" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-13.97" y1="-1.905" x2="-13.97" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-13.97" y1="0.635" x2="-16.51" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-15.24" y1="6.985" x2="-15.24" y2="1.27" width="0.762" layer="21"/>
<wire x1="-13.97" y1="-1.905" x2="-11.43" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-11.43" y1="-1.905" x2="-11.43" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-11.43" y1="0.635" x2="-13.97" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-12.7" y1="6.985" x2="-12.7" y2="1.27" width="0.762" layer="21"/>
<wire x1="-11.43" y1="-1.905" x2="-8.89" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-8.89" y1="-1.905" x2="-8.89" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-8.89" y1="0.635" x2="-11.43" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-10.16" y1="6.985" x2="-10.16" y2="1.27" width="0.762" layer="21"/>
<wire x1="-8.89" y1="-1.905" x2="-6.35" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-6.35" y1="-1.905" x2="-6.35" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-6.35" y1="0.635" x2="-8.89" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-7.62" y1="6.985" x2="-7.62" y2="1.27" width="0.762" layer="21"/>
<wire x1="-6.35" y1="-1.905" x2="-3.81" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-3.81" y1="-1.905" x2="-3.81" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-3.81" y1="0.635" x2="-6.35" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-5.08" y1="6.985" x2="-5.08" y2="1.27" width="0.762" layer="21"/>
<wire x1="-3.81" y1="-1.905" x2="-1.27" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="-1.27" y1="-1.905" x2="-1.27" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-1.27" y1="0.635" x2="-3.81" y2="0.635" width="0.1524" layer="21"/>
<wire x1="-2.54" y1="6.985" x2="-2.54" y2="1.27" width="0.762" layer="21"/>
<wire x1="-1.27" y1="-1.905" x2="1.27" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="1.27" y1="-1.905" x2="1.27" y2="0.635" width="0.1524" layer="21"/>
<wire x1="1.27" y1="0.635" x2="-1.27" y2="0.635" width="0.1524" layer="21"/>
<wire x1="0" y1="6.985" x2="0" y2="1.27" width="0.762" layer="21"/>
<wire x1="1.27" y1="-1.905" x2="3.81" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="3.81" y1="-1.905" x2="3.81" y2="0.635" width="0.1524" layer="21"/>
<wire x1="3.81" y1="0.635" x2="1.27" y2="0.635" width="0.1524" layer="21"/>
<wire x1="2.54" y1="6.985" x2="2.54" y2="1.27" width="0.762" layer="21"/>
<wire x1="3.81" y1="-1.905" x2="6.35" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="6.35" y1="-1.905" x2="6.35" y2="0.635" width="0.1524" layer="21"/>
<wire x1="6.35" y1="0.635" x2="3.81" y2="0.635" width="0.1524" layer="21"/>
<wire x1="5.08" y1="6.985" x2="5.08" y2="1.27" width="0.762" layer="21"/>
<wire x1="6.35" y1="-1.905" x2="8.89" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="8.89" y1="-1.905" x2="8.89" y2="0.635" width="0.1524" layer="21"/>
<wire x1="8.89" y1="0.635" x2="6.35" y2="0.635" width="0.1524" layer="21"/>
<wire x1="7.62" y1="6.985" x2="7.62" y2="1.27" width="0.762" layer="21"/>
<wire x1="8.89" y1="-1.905" x2="11.43" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="11.43" y1="-1.905" x2="11.43" y2="0.635" width="0.1524" layer="21"/>
<wire x1="11.43" y1="0.635" x2="8.89" y2="0.635" width="0.1524" layer="21"/>
<wire x1="10.16" y1="6.985" x2="10.16" y2="1.27" width="0.762" layer="21"/>
<wire x1="11.43" y1="-1.905" x2="13.97" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="13.97" y1="-1.905" x2="13.97" y2="0.635" width="0.1524" layer="21"/>
<wire x1="13.97" y1="0.635" x2="11.43" y2="0.635" width="0.1524" layer="21"/>
<wire x1="12.7" y1="6.985" x2="12.7" y2="1.27" width="0.762" layer="21"/>
<wire x1="13.97" y1="-1.905" x2="16.51" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="16.51" y1="-1.905" x2="16.51" y2="0.635" width="0.1524" layer="21"/>
<wire x1="16.51" y1="0.635" x2="13.97" y2="0.635" width="0.1524" layer="21"/>
<wire x1="15.24" y1="6.985" x2="15.24" y2="1.27" width="0.762" layer="21"/>
<wire x1="16.51" y1="-1.905" x2="19.05" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="19.05" y1="-1.905" x2="19.05" y2="0.635" width="0.1524" layer="21"/>
<wire x1="19.05" y1="0.635" x2="16.51" y2="0.635" width="0.1524" layer="21"/>
<wire x1="17.78" y1="6.985" x2="17.78" y2="1.27" width="0.762" layer="21"/>
<wire x1="19.05" y1="-1.905" x2="21.59" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="21.59" y1="-1.905" x2="21.59" y2="0.635" width="0.1524" layer="21"/>
<wire x1="21.59" y1="0.635" x2="19.05" y2="0.635" width="0.1524" layer="21"/>
<wire x1="20.32" y1="6.985" x2="20.32" y2="1.27" width="0.762" layer="21"/>
<wire x1="21.59" y1="-1.905" x2="24.13" y2="-1.905" width="0.1524" layer="21"/>
<wire x1="24.13" y1="-1.905" x2="24.13" y2="0.635" width="0.1524" layer="21"/>
<wire x1="24.13" y1="0.635" x2="21.59" y2="0.635" width="0.1524" layer="21"/>
<wire x1="22.86" y1="6.985" x2="22.86" y2="1.27" width="0.762" layer="21"/>
<pad name="1" x="-22.86" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="2" x="-20.32" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="3" x="-17.78" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="4" x="-15.24" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="5" x="-12.7" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="6" x="-10.16" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="7" x="-7.62" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="8" x="-5.08" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="9" x="-2.54" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="10" x="0" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="11" x="2.54" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="12" x="5.08" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="13" x="7.62" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="14" x="10.16" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="15" x="12.7" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="16" x="15.24" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="17" x="17.78" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="18" x="20.32" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<pad name="19" x="22.86" y="-3.81" drill="1.016" shape="long" rot="R90"/>
<text x="-24.765" y="-3.81" size="1.27" layer="25" ratio="10" rot="R90">&gt;NAME</text>
<text x="26.035" y="-3.81" size="1.27" layer="27" rot="R90">&gt;VALUE</text>
<rectangle x1="-23.241" y1="0.635" x2="-22.479" y2="1.143" layer="21"/>
<rectangle x1="-20.701" y1="0.635" x2="-19.939" y2="1.143" layer="21"/>
<rectangle x1="-18.161" y1="0.635" x2="-17.399" y2="1.143" layer="21"/>
<rectangle x1="-15.621" y1="0.635" x2="-14.859" y2="1.143" layer="21"/>
<rectangle x1="-13.081" y1="0.635" x2="-12.319" y2="1.143" layer="21"/>
<rectangle x1="-10.541" y1="0.635" x2="-9.779" y2="1.143" layer="21"/>
<rectangle x1="-8.001" y1="0.635" x2="-7.239" y2="1.143" layer="21"/>
<rectangle x1="-5.461" y1="0.635" x2="-4.699" y2="1.143" layer="21"/>
<rectangle x1="-2.921" y1="0.635" x2="-2.159" y2="1.143" layer="21"/>
<rectangle x1="-0.381" y1="0.635" x2="0.381" y2="1.143" layer="21"/>
<rectangle x1="2.159" y1="0.635" x2="2.921" y2="1.143" layer="21"/>
<rectangle x1="4.699" y1="0.635" x2="5.461" y2="1.143" layer="21"/>
<rectangle x1="7.239" y1="0.635" x2="8.001" y2="1.143" layer="21"/>
<rectangle x1="9.779" y1="0.635" x2="10.541" y2="1.143" layer="21"/>
<rectangle x1="12.319" y1="0.635" x2="13.081" y2="1.143" layer="21"/>
<rectangle x1="14.859" y1="0.635" x2="15.621" y2="1.143" layer="21"/>
<rectangle x1="17.399" y1="0.635" x2="18.161" y2="1.143" layer="21"/>
<rectangle x1="19.939" y1="0.635" x2="20.701" y2="1.143" layer="21"/>
<rectangle x1="22.479" y1="0.635" x2="23.241" y2="1.143" layer="21"/>
<rectangle x1="-23.241" y1="-2.921" x2="-22.479" y2="-1.905" layer="21"/>
<rectangle x1="-20.701" y1="-2.921" x2="-19.939" y2="-1.905" layer="21"/>
<rectangle x1="-18.161" y1="-2.921" x2="-17.399" y2="-1.905" layer="21"/>
<rectangle x1="-15.621" y1="-2.921" x2="-14.859" y2="-1.905" layer="21"/>
<rectangle x1="-13.081" y1="-2.921" x2="-12.319" y2="-1.905" layer="21"/>
<rectangle x1="-10.541" y1="-2.921" x2="-9.779" y2="-1.905" layer="21"/>
<rectangle x1="-8.001" y1="-2.921" x2="-7.239" y2="-1.905" layer="21"/>
<rectangle x1="-5.461" y1="-2.921" x2="-4.699" y2="-1.905" layer="21"/>
<rectangle x1="-2.921" y1="-2.921" x2="-2.159" y2="-1.905" layer="21"/>
<rectangle x1="-0.381" y1="-2.921" x2="0.381" y2="-1.905" layer="21"/>
<rectangle x1="2.159" y1="-2.921" x2="2.921" y2="-1.905" layer="21"/>
<rectangle x1="4.699" y1="-2.921" x2="5.461" y2="-1.905" layer="21"/>
<rectangle x1="7.239" y1="-2.921" x2="8.001" y2="-1.905" layer="21"/>
<rectangle x1="9.779" y1="-2.921" x2="10.541" y2="-1.905" layer="21"/>
<rectangle x1="12.319" y1="-2.921" x2="13.081" y2="-1.905" layer="21"/>
<rectangle x1="14.859" y1="-2.921" x2="15.621" y2="-1.905" layer="21"/>
<rectangle x1="17.399" y1="-2.921" x2="18.161" y2="-1.905" layer="21"/>
<rectangle x1="19.939" y1="-2.921" x2="20.701" y2="-1.905" layer="21"/>
<rectangle x1="22.479" y1="-2.921" x2="23.241" y2="-1.905" layer="21"/>
</package>
</packages>
<symbols>
<symbol name="PINHD19">
<wire x1="-6.35" y1="-27.94" x2="1.27" y2="-27.94" width="0.4064" layer="94"/>
<wire x1="1.27" y1="-27.94" x2="1.27" y2="22.86" width="0.4064" layer="94"/>
<wire x1="1.27" y1="22.86" x2="-6.35" y2="22.86" width="0.4064" layer="94"/>
<wire x1="-6.35" y1="22.86" x2="-6.35" y2="-27.94" width="0.4064" layer="94"/>
<text x="-6.35" y="23.495" size="1.778" layer="95">&gt;NAME</text>
<text x="-6.35" y="-30.48" size="1.778" layer="96">&gt;VALUE</text>
<pin name="1" x="-2.54" y="20.32" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="2" x="-2.54" y="17.78" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="3" x="-2.54" y="15.24" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="4" x="-2.54" y="12.7" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="5" x="-2.54" y="10.16" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="6" x="-2.54" y="7.62" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="7" x="-2.54" y="5.08" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="8" x="-2.54" y="2.54" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="9" x="-2.54" y="0" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="10" x="-2.54" y="-2.54" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="11" x="-2.54" y="-5.08" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="12" x="-2.54" y="-7.62" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="13" x="-2.54" y="-10.16" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="14" x="-2.54" y="-12.7" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="15" x="-2.54" y="-15.24" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="16" x="-2.54" y="-17.78" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="17" x="-2.54" y="-20.32" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="18" x="-2.54" y="-22.86" visible="pad" length="short" direction="pas" function="dot"/>
<pin name="19" x="-2.54" y="-25.4" visible="pad" length="short" direction="pas" function="dot"/>
</symbol>
</symbols>
<devicesets>
<deviceset name="PINHD-1X19" prefix="JP" uservalue="yes">
<description>&lt;b&gt;PIN HEADER&lt;/b&gt;</description>
<gates>
<gate name="G$1" symbol="PINHD19" x="0" y="0"/>
</gates>
<devices>
<device name="" package="1X19">
<connects>
<connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="10" pad="10"/>
<connect gate="G$1" pin="11" pad="11"/>
<connect gate="G$1" pin="12" pad="12"/>
<connect gate="G$1" pin="13" pad="13"/>
<connect gate="G$1" pin="14" pad="14"/>
<connect gate="G$1" pin="15" pad="15"/>
<connect gate="G$1" pin="16" pad="16"/>
<connect gate="G$1" pin="17" pad="17"/>
<connect gate="G$1" pin="18" pad="18"/>
<connect gate="G$1" pin="19" pad="19"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/>
<connect gate="G$1" pin="4" pad="4"/>
<connect gate="G$1" pin="5" pad="5"/>
<connect gate="G$1" pin="6" pad="6"/>
<connect gate="G$1" pin="7" pad="7"/>
<connect gate="G$1" pin="8" pad="8"/>
<connect gate="G$1" pin="9" pad="9"/>
</connects>
<technologies>
<technology name=""/>
</technologies>
</device>
<device name="/90" package="1X19/90">
<connects>
<connect gate="G$1" pin="1" pad="1"/>
<connect gate="G$1" pin="10" pad="10"/>
<connect gate="G$1" pin="11" pad="11"/>
<connect gate="G$1" pin="12" pad="12"/>
<connect gate="G$1" pin="13" pad="13"/>
<connect gate="G$1" pin="14" pad="14"/>
<connect gate="G$1" pin="15" pad="15"/>
<connect gate="G$1" pin="16" pad="16"/>
<connect gate="G$1" pin="17" pad="17"/>
<connect gate="G$1" pin="18" pad="18"/>
<connect gate="G$1" pin="19" pad="19"/>
<connect gate="G$1" pin="2" pad="2"/>
<connect gate="G$1" pin="3" pad="3"/>
<connect gate="G$1" pin="4" pad="4"/>
<connect gate="G$1" pin="5" pad="5"/>
<connect gate="G$1" pin="6" pad="6"/>
<connect gate="G$1" pin="7" pad="7"/>
<connect gate="G$1" pin="8" pad="8"/>
<connect gate="G$1" pin="9" pad="9"/>
</connects>
<technologies>
<technology name=""/>
</technologies>
</device>
</devices>
</deviceset>
</devicesets>
</library>
</libraries>
<attributes>
</attributes>
<variantdefs>
</variantdefs>
<classes>
<class number="0" name="default" width="0" drill="0">
</class>
</classes>
<parts>
<part name="IC1" library="texas" deviceset="MSP430F22*4IDA" device="" technology="7"/>
<part name="JP1" library="pinhead" deviceset="PINHD-1X19" device=""/>
<part name="JP2" library="pinhead" deviceset="PINHD-1X19" device=""/>
</parts>
<sheets>
<sheet>
<plain>
</plain>
<instances>
<instance part="IC1" gate="G$1" x="-2.54" y="58.42"/>
<instance part="JP1" gate="G$1" x="-38.1" y="-7.62"/>
<instance part="JP2" gate="G$1" x="38.1" y="-12.7" rot="R180"/>
</instances>
<busses>
</busses>
<nets>
<net name="N$1" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="TEST/SBWTCK"/>
<wire x1="-50.8" y1="81.28" x2="-106.68" y2="81.28" width="0.1524" layer="91"/>
<wire x1="-106.68" y1="81.28" x2="-106.68" y2="12.7" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="1"/>
<wire x1="-106.68" y1="12.7" x2="-40.64" y2="12.7" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$2" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="DVCC"/>
<wire x1="-50.8" y1="78.74" x2="-104.14" y2="78.74" width="0.1524" layer="91"/>
<wire x1="-104.14" y1="78.74" x2="-104.14" y2="10.16" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="2"/>
<wire x1="-104.14" y1="10.16" x2="-40.64" y2="10.16" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$3" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P2.5/ROSC"/>
<wire x1="-50.8" y1="76.2" x2="-101.6" y2="76.2" width="0.1524" layer="91"/>
<wire x1="-101.6" y1="76.2" x2="-101.6" y2="7.62" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="3"/>
<wire x1="-101.6" y1="7.62" x2="-40.64" y2="7.62" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$4" class="0">
<segment>
<wire x1="-99.06" y1="73.66" x2="-99.06" y2="5.08" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="4"/>
<wire x1="-99.06" y1="5.08" x2="-40.64" y2="5.08" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="DVSS"/>
<wire x1="-50.8" y1="73.66" x2="-99.06" y2="73.66" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$5" class="0">
<segment>
<pinref part="JP1" gate="G$1" pin="5"/>
<wire x1="-40.64" y1="2.54" x2="-96.52" y2="2.54" width="0.1524" layer="91"/>
<wire x1="-96.52" y1="2.54" x2="-96.52" y2="71.12" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="XOUT/P2.7"/>
<wire x1="-96.52" y1="71.12" x2="-50.8" y2="71.12" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$6" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="XIN/P2.6"/>
<wire x1="-50.8" y1="68.58" x2="-93.98" y2="68.58" width="0.1524" layer="91"/>
<wire x1="-93.98" y1="68.58" x2="-93.98" y2="0" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="6"/>
<wire x1="-93.98" y1="0" x2="-40.64" y2="0" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$7" class="0">
<segment>
<pinref part="JP1" gate="G$1" pin="7"/>
<wire x1="-40.64" y1="-2.54" x2="-91.44" y2="-2.54" width="0.1524" layer="91"/>
<wire x1="-91.44" y1="-2.54" x2="-91.44" y2="66.04" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="!RST!/NMI/SBWTDIO"/>
<wire x1="-50.8" y1="66.04" x2="-91.44" y2="66.04" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$8" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P2.0/ACLK/A0/OA0I0"/>
<wire x1="-50.8" y1="63.5" x2="-88.9" y2="63.5" width="0.1524" layer="91"/>
<wire x1="-88.9" y1="63.5" x2="-88.9" y2="-5.08" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="8"/>
<wire x1="-88.9" y1="-5.08" x2="-40.64" y2="-5.08" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$9" class="0">
<segment>
<pinref part="JP1" gate="G$1" pin="9"/>
<wire x1="-40.64" y1="-7.62" x2="-86.36" y2="-7.62" width="0.1524" layer="91"/>
<wire x1="-86.36" y1="-7.62" x2="-86.36" y2="60.96" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P2.1/TAINCLK/SMCLK/A1/OA0O"/>
<wire x1="-86.36" y1="60.96" x2="-50.8" y2="60.96" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$10" class="0">
<segment>
<wire x1="-83.82" y1="58.42" x2="-83.82" y2="-10.16" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="10"/>
<wire x1="-83.82" y1="-10.16" x2="-40.64" y2="-10.16" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P2.2/TA0/A2/OA0I1"/>
<wire x1="-50.8" y1="58.42" x2="-83.82" y2="58.42" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$11" class="0">
<segment>
<pinref part="JP1" gate="G$1" pin="11"/>
<wire x1="-40.64" y1="-12.7" x2="-81.28" y2="-12.7" width="0.1524" layer="91"/>
<wire x1="-81.28" y1="-12.7" x2="-81.28" y2="55.88" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P3.0/UCB0STE/UCA0CLK/A5"/>
<wire x1="-81.28" y1="55.88" x2="-50.8" y2="55.88" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$12" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P3.1/UCB0SIMO/UCB0SDA"/>
<wire x1="-50.8" y1="53.34" x2="-78.74" y2="53.34" width="0.1524" layer="91"/>
<wire x1="-78.74" y1="53.34" x2="-78.74" y2="-15.24" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="12"/>
<wire x1="-78.74" y1="-15.24" x2="-40.64" y2="-15.24" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$13" class="0">
<segment>
<pinref part="JP1" gate="G$1" pin="13"/>
<wire x1="-40.64" y1="-17.78" x2="-76.2" y2="-17.78" width="0.1524" layer="91"/>
<wire x1="-76.2" y1="-17.78" x2="-76.2" y2="50.8" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P3.2/UCB0SOMI/UCB0SCL"/>
<wire x1="-76.2" y1="50.8" x2="-50.8" y2="50.8" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$14" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P3.3/UCB0CLK/UCA0STE"/>
<wire x1="-50.8" y1="48.26" x2="-73.66" y2="48.26" width="0.1524" layer="91"/>
<wire x1="-73.66" y1="48.26" x2="-73.66" y2="-20.32" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="14"/>
<wire x1="-73.66" y1="-20.32" x2="-40.64" y2="-20.32" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$15" class="0">
<segment>
<pinref part="JP1" gate="G$1" pin="15"/>
<wire x1="-40.64" y1="-22.86" x2="-71.12" y2="-22.86" width="0.1524" layer="91"/>
<wire x1="-71.12" y1="-22.86" x2="-71.12" y2="45.72" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="AVSS"/>
<wire x1="-71.12" y1="45.72" x2="-50.8" y2="45.72" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$16" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="AVCC"/>
<wire x1="-50.8" y1="43.18" x2="-68.58" y2="43.18" width="0.1524" layer="91"/>
<wire x1="-68.58" y1="43.18" x2="-68.58" y2="-25.4" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="16"/>
<wire x1="-68.58" y1="-25.4" x2="-40.64" y2="-25.4" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$17" class="0">
<segment>
<pinref part="JP1" gate="G$1" pin="17"/>
<wire x1="-40.64" y1="-27.94" x2="-66.04" y2="-27.94" width="0.1524" layer="91"/>
<wire x1="-66.04" y1="-27.94" x2="-66.04" y2="40.64" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P4.0/TB0"/>
<wire x1="-66.04" y1="40.64" x2="-50.8" y2="40.64" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$18" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P4.1/TB1"/>
<wire x1="-50.8" y1="38.1" x2="-63.5" y2="38.1" width="0.1524" layer="91"/>
<wire x1="-63.5" y1="38.1" x2="-63.5" y2="-30.48" width="0.1524" layer="91"/>
<pinref part="JP1" gate="G$1" pin="18"/>
<wire x1="-63.5" y1="-30.48" x2="-40.64" y2="-30.48" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$19" class="0">
<segment>
<pinref part="JP1" gate="G$1" pin="19"/>
<wire x1="-40.64" y1="-33.02" x2="-60.96" y2="-33.02" width="0.1524" layer="91"/>
<wire x1="-60.96" y1="-33.02" x2="-60.96" y2="35.56" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P4.2/TB2"/>
<wire x1="-60.96" y1="35.56" x2="-50.8" y2="35.56" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$20" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P1.7/TA2/TDO/TDI"/>
<wire x1="45.72" y1="81.28" x2="106.68" y2="81.28" width="0.1524" layer="91"/>
<wire x1="106.68" y1="81.28" x2="106.68" y2="12.7" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="19"/>
<wire x1="106.68" y1="12.7" x2="40.64" y2="12.7" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$21" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P1.6/TA1/TDI/TCLK"/>
<wire x1="45.72" y1="78.74" x2="104.14" y2="78.74" width="0.1524" layer="91"/>
<wire x1="104.14" y1="78.74" x2="104.14" y2="10.16" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="18"/>
<wire x1="104.14" y1="10.16" x2="40.64" y2="10.16" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$22" class="0">
<segment>
<pinref part="JP2" gate="G$1" pin="17"/>
<wire x1="40.64" y1="7.62" x2="101.6" y2="7.62" width="0.1524" layer="91"/>
<wire x1="101.6" y1="7.62" x2="101.6" y2="76.2" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P1.5/TA0/TMS"/>
<wire x1="101.6" y1="76.2" x2="45.72" y2="76.2" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$23" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P1.4/SMCLK/TCK"/>
<wire x1="45.72" y1="73.66" x2="99.06" y2="73.66" width="0.1524" layer="91"/>
<wire x1="99.06" y1="73.66" x2="99.06" y2="5.08" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="16"/>
<wire x1="99.06" y1="5.08" x2="40.64" y2="5.08" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$24" class="0">
<segment>
<pinref part="JP2" gate="G$1" pin="15"/>
<wire x1="40.64" y1="2.54" x2="96.52" y2="2.54" width="0.1524" layer="91"/>
<wire x1="96.52" y1="2.54" x2="96.52" y2="71.12" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P1.3/TA2"/>
<wire x1="45.72" y1="71.12" x2="96.52" y2="71.12" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$25" class="0">
<segment>
<wire x1="93.98" y1="68.58" x2="93.98" y2="0" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="14"/>
<wire x1="93.98" y1="0" x2="40.64" y2="0" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P1.2/TA1"/>
<wire x1="93.98" y1="68.58" x2="45.72" y2="68.58" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$26" class="0">
<segment>
<pinref part="JP2" gate="G$1" pin="13"/>
<wire x1="40.64" y1="-2.54" x2="91.44" y2="-2.54" width="0.1524" layer="91"/>
<wire x1="91.44" y1="-2.54" x2="91.44" y2="66.04" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P1.1/TA0"/>
<wire x1="45.72" y1="66.04" x2="91.44" y2="66.04" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$27" class="0">
<segment>
<wire x1="88.9" y1="63.5" x2="88.9" y2="-5.08" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="12"/>
<wire x1="88.9" y1="-5.08" x2="40.64" y2="-5.08" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P1.0/TACLK/ADC10CLK"/>
<wire x1="88.9" y1="63.5" x2="45.72" y2="63.5" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$28" class="0">
<segment>
<pinref part="JP2" gate="G$1" pin="11"/>
<wire x1="40.64" y1="-7.62" x2="86.36" y2="-7.62" width="0.1524" layer="91"/>
<wire x1="86.36" y1="-7.62" x2="86.36" y2="60.96" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P2.4/TA2/A4/VREF+/VEREF+/OA1I0"/>
<wire x1="45.72" y1="60.96" x2="86.36" y2="60.96" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$29" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P2.3/TA1/A3/VREF-/VEREF-/OA1I1/OA1O"/>
<wire x1="45.72" y1="58.42" x2="83.82" y2="58.42" width="0.1524" layer="91"/>
<wire x1="83.82" y1="58.42" x2="83.82" y2="-10.16" width="0.1524" layer="91"/>
<wire x1="83.82" y1="-10.16" x2="40.64" y2="-10.16" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="10"/>
<wire x1="38.1" y1="-10.16" x2="40.64" y2="-10.16" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$30" class="0">
<segment>
<pinref part="JP2" gate="G$1" pin="9"/>
<wire x1="40.64" y1="-12.7" x2="81.28" y2="-12.7" width="0.1524" layer="91"/>
<wire x1="81.28" y1="-12.7" x2="81.28" y2="55.88" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P3.7/A7/OA1I2"/>
<wire x1="81.28" y1="55.88" x2="45.72" y2="55.88" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$31" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P3.6/A6/OA0I2"/>
<wire x1="45.72" y1="53.34" x2="78.74" y2="53.34" width="0.1524" layer="91"/>
<wire x1="78.74" y1="53.34" x2="78.74" y2="-15.24" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="8"/>
<wire x1="78.74" y1="-15.24" x2="40.64" y2="-15.24" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$32" class="0">
<segment>
<pinref part="JP2" gate="G$1" pin="7"/>
<wire x1="40.64" y1="-17.78" x2="76.2" y2="-17.78" width="0.1524" layer="91"/>
<wire x1="76.2" y1="-17.78" x2="76.2" y2="50.8" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P3.5/UCA0RXD/UCA0SOMI"/>
<wire x1="76.2" y1="50.8" x2="45.72" y2="50.8" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$33" class="0">
<segment>
<pinref part="IC1" gate="G$1" pin="P3.4/UCA0TXD/UCA0SIMO"/>
<wire x1="45.72" y1="48.26" x2="73.66" y2="48.26" width="0.1524" layer="91"/>
<wire x1="73.66" y1="48.26" x2="73.66" y2="-20.32" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="6"/>
<wire x1="73.66" y1="-20.32" x2="40.64" y2="-20.32" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$34" class="0">
<segment>
<pinref part="JP2" gate="G$1" pin="5"/>
<wire x1="40.64" y1="-22.86" x2="71.12" y2="-22.86" width="0.1524" layer="91"/>
<wire x1="71.12" y1="-22.86" x2="71.12" y2="45.72" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P4.7/TBCLK"/>
<wire x1="45.72" y1="45.72" x2="71.12" y2="45.72" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$35" class="0">
<segment>
<wire x1="68.58" y1="43.18" x2="68.58" y2="-25.4" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="4"/>
<wire x1="68.58" y1="-25.4" x2="40.64" y2="-25.4" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P4.6/TBOUTHA15/OA1I3"/>
<wire x1="68.58" y1="43.18" x2="45.72" y2="43.18" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$36" class="0">
<segment>
<pinref part="JP2" gate="G$1" pin="3"/>
<wire x1="40.64" y1="-27.94" x2="66.04" y2="-27.94" width="0.1524" layer="91"/>
<wire x1="66.04" y1="-27.94" x2="66.04" y2="40.64" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P4.5/TB2A14/OA0I3"/>
<wire x1="45.72" y1="40.64" x2="66.04" y2="40.64" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$37" class="0">
<segment>
<wire x1="63.5" y1="38.1" x2="63.5" y2="-30.48" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P4.4/TB1A13/OA1O"/>
<wire x1="63.5" y1="38.1" x2="45.72" y2="38.1" width="0.1524" layer="91"/>
<pinref part="JP2" gate="G$1" pin="2"/>
<wire x1="40.64" y1="-30.48" x2="63.5" y2="-30.48" width="0.1524" layer="91"/>
</segment>
</net>
<net name="N$38" class="0">
<segment>
<pinref part="JP2" gate="G$1" pin="1"/>
<wire x1="40.64" y1="-33.02" x2="60.96" y2="-33.02" width="0.1524" layer="91"/>
<wire x1="60.96" y1="-33.02" x2="60.96" y2="35.56" width="0.1524" layer="91"/>
<pinref part="IC1" gate="G$1" pin="P4.3/TB0/A12/OA0O"/>
<wire x1="45.72" y1="35.56" x2="60.96" y2="35.56" width="0.1524" layer="91"/>
</segment>
</net>
</nets>
</sheet>
</sheets>
</schematic>
</drawing>
</eagle>
